### ISSUE TITLE
Introduce `moz-webgpu-cts process-reports`

### ISSUE THREAD

**Issue by ErichDonGubler** [ErichDonGubler/moz-webgpu-cts#13]
As the developer of Firefox implementation of WebGPU, it's sometimes difficult to quickly adjust test expectations after I make changes to Firefox. CTS comprises a large set of tests and files that I work with, and it can be time-consuming and even error-prone to find the right places in files to edit by hand when I receive WPT reports from CI.

I would like tool assistance in adjusting expectations in the correct locations, given a set of WPT reports in JSON format (i.e., `wptreport.json`) files that are provided by CTS runs in CI (`./mach wpt --log-wptreport=…`). I recognize that there are different heuristics that I may want to use for adjusting expected outcomes, so I'll offer users their choice of adjustment heuristic. The data I'll use is:

1. WPT metadata files underneath `testing/web-platform/mozilla/meta/webgpu`. Per test and subtest, there will be a set of expected outcomes per platform.
2. One or more WPT execution reports. For tests relevant to WebGPU, there will be tests within the `webgpu` test path that have actual outcomes on a specific platform noted. These can be combined to form a set of actual outcomes in a structure otherwise very similar to (1).

## Overall flow of `moz-webgpu-cts process-reports`

The flow of the tool should be:

1. Gather a bunch of WPT reports using a tool like `./mach wpt-fetch-logs try:2639473c8ba1d33e13a3108db7660cc8cbed91f5` or (eventually) #18.
1. Invoke `moz-webgpu-cts process-reports --preset=… <wpt-report-json-paths…>`
    1. Note that we are specifying a `--preset=…` here. This is a required argument to specify a heuristic for making changes based on reports. Presets are intended to be very coarse grained configurations that match typical workflows for convenience. We do not provide other options for finer-grained configuration at this time, but we plan to do so, and track progress on such at #26.
    1. Also accept 0 or more `--glob <glob>` options, which correspond to [`wax`](https://docs.rs/wax/0.6.0) globs.
    1. Validate that the base name of each file path passed directly or yielded by the glob ends with `wptreport.json`. If any paths fail validation, emit a warning on `stderr`.
1. Gather data sets (1) and (2), as noted above. Data set (2) will be derived from file paths to JSON blobs containing WPT reports that are enumerated in the previous step.
    1. If there are any parsing or validation errors with either data set, then bail on the entire invocation with a set of error(s) that seem appropriate.
1. Compare expected test and subtest outcomes in metadata with reported outcomes by platform and build profile. Use the provided `--preset=…` to determine how to react in each comparison case.
	1. For this MVP, it is acceptable if all metadata files are re-emitted, even when not substantially changed; such a case would be as if somebody invoked the `fmt` subcommand (see #8).
	1. EDIT: [already implemented](https://github.com/ErichDonGubler/moz-webgpu-cts/issues/13#issuecomment-1791117873).

## Technical notes

Fortunately, we have a lot of good data to work with. We already implement parsing of WPT metadata as of #5, so the remaining work is:

- [x] Parse WPT execution reports from JSON
- [x] Perform comparisons between expected and actual outcomes
- [x] Adjust `moz-webgpu-cts fmt` to restructure metadata as described in "Overall flow of `moz-webgpu-cts process-reports`", requirement 4.ii. EDIT: [Done](https://github.com/ErichDonGubler/moz-webgpu-cts/issues/13#issuecomment-1791117873) with #39 and #43.

**Comment by jimblandy** [comment]
For reconciliation, it might suffice to let the user choose overall behavior via command-line flags, but just write out the new WPT metadata files, and let them use git/hg to inspect and reconcile. git/hg already have excellent support for viewing and selecting changes. This might be unwieldy in some cases, but it seems adequate for an MVP.

**Comment by ErichDonGubler** [comment]
@jimblandy: Hmm…I agree that investing in a prompt flow might not be prudent right now. The motivating factor was having a better flow than `{hg,git} diff` currently offer for diffs where the context around a hunk does not indicate which test path changes apply to. Perhaps this can be achieved with a separate Git diff driver, which would be a more general tool? Assuming so, then yes, I don't see a reason not to offer completely automated heuristics first, and forgo potentially complicated UX questions for low-hanging fruit.

**Comment by ErichDonGubler** [comment]
Aha, I was actually able to get much of the same effective with the following `.gitconfig` snippet:

```
[diff "wpt-metadata"]
	xfuncname = "^\\[.*\\]\\s*$"
```

…and the following `.gitattributes` snippet:

```
testing/web-platform/meta/**/*.ini diff=wpt-metadata
testing/web-platform/mozilla/meta/**/*.ini diff=wpt-metadata
```

…which yields output like this:

```diff
diff --git a/testing/web-platform/mozilla/meta/webgpu/chunked/20/cts.https.html.ini b/testing/web-platform/mozilla/meta/webgpu/chunked/20/cts.https.html.ini
index b51d7fe6de28a..ea93b2101d342 100644
--- a/testing/web-platform/mozilla/meta/webgpu/chunked/20/cts.https.html.ini
+++ b/testing/web-platform/mozilla/meta/webgpu/chunked/20/cts.https.html.ini
@@ -48,6 +48,7 @@ [cts.https.html?q=webgpu:api,validation,encoding,cmds,setBindGroup:dynamic_offse
   [:encoderType="compute%20pass";dynamicOffsets=[\];useU32array=true]
     expected:
       if os == "mac": FAIL
+      blarg
 
   [:encoderType="compute%20pass";dynamicOffsets=[512,0\];useU32array=false]
     expected:
```

Note the hunk header output that's showing the test section header a few dozen lines up in source (!):

```
@@ -48,6 +48,7 @@ [cts.https.html?q=webgpu:api,validation,encoding,cmds,setBindGroup:dynamic_offse
```

…so yep, I don't see a reason not to go with fully automated adjustment heuristics for now. I'll probably change this issue to be an implementation

**Comment by ErichDonGubler** [comment]
4.ii has been broken out to #39 and #43, and is no longer needed. Will leave a struck-out placeholder to not re-use the requirement index. FTR, the text was:

> 1. We should not try to make configurable behavior for the structure of conditional `expected` properties. Therefore, we'll introduce an opinion on how this structure[^2] should be normalized when metadata is changed. Normalize according to the following rules:
>
>     1. Maintain a total order of tests and subtests, as `fmt` currently does.
>     1. Do not use conditional fallback rules. Prefer to enumerate outcomes by (1) platform and then (2) build profiles explicitly, rather than assume that other platforms will have the same outcomes.
>         1. Where possible, collapse conditional rules down to a single platform or even to a single unconditional property value. Intermittent outcomes with the same set of outcomes but different ordering should still be collapsed.
>     1. Always omit `PASS` outcomes. Explicit `PASS`es don't seem to offer any clarity in the context of other rules specified here.
>
> Examples of "normalized" metadata are as follows:
>
> ```ini
> [windows-fails]
>   [subtest]
>     expected:
>       if os == "win": FAIL
>
> [two-targets-fail]
>   [subtest]
>     expected:
>       if os == "win": FAIL
>       if os == "linux" and debug: FAIL
>
> [all-platforms-fail]
>   [subtest]
>   expected: FAIL
> ```
>
> The following are examples of incorrect structure:
>
> ```
> # Prefer to omit explicit `PASS`es where possible.
>
> [windows-fails-1]
>   [subtest]
>     expected:
>       if os == "win": FAIL
>       PASS
>
> [two-targets-fail]
>   [subtest]
>     expected:
>       if os == "mac": PASS
>       if os == "linux" and not debug: PASS
>       FAIL
>
> # We should coalesce into a single unconditional result where possible.
>
> [all-platforms-fail]
>   [subtest]
>     expected:
>       if os == "win": FAIL
>       if os == "linux": FAIL
>       if os == "mac": FAIL
>
> [windows-fails-2]
>   [subtest]
>     expected:
>       if os == "win" and debug: FAIL
>       if os == "win" and not debug: FAIL
> ```

**Comment by ErichDonGubler** [comment]
I have removed the <code>Behavior of `--on-conflict=change-to-reported`</code> section from the OP, since implementation now has documentation I consider better for understanding and smithing requirements.
