### ISSUE TITLE
Errors on parsing valid metadata

### ISSUE THREAD

**Issue by sagudev** [ErichDonGubler/moz-webgpu-cts#79]
Example [expectation](https://github.com/ErichDonGubler/moz-webgpu-cts/files/14298684/canvas_complex_rgba8unorm_store.https.html.ini.txt):
```
[canvas_complex_rgba8unorm_store.https.html]
  expected: FAIL

```
gives

```
× found ' ' expected test section header, or indentation at the proper level
   ╭─[/servo/tests/wpt/webgpu/meta/webgpu/webgpu/web_platform/reftests/canvas_complex_rgba8unorm_store.https.html.ini:1:1]
 1 │ [canvas_complex_rgba8unorm_store.https.html]
 2 │   expected: FAIL
   · ─
   ╰────
```

**Comment by sagudev** [comment]
I think it's happening because it's not expecting `FAIL` as expectation for test but only for subtests. Relevant code: https://github.com/ErichDonGubler/moz-webgpu-cts/blob/a82d347bb86f3dfb801b1d56fb22422f476715f4/moz-webgpu-cts/src/metadata.rs#L978-L984

**Comment by sagudev** [comment]
https://github.com/ErichDonGubler/moz-webgpu-cts/pull/80/commits/e90940f21efb0748346c2e87c9d3954417392711 now fixes metadata parser. The only thing missing is analyzer stuff for tests_with_fails.

**Comment by sagudev** [comment]
Still fails on:
```
[canvas_composite_alpha_bgra8unorm_opaque_draw.https.html]
  expected: [PASS, FAIL, CRASH]
```
so we will probably need to handle such cases as subtest altogether.

Also failure on `disabled` (because it's valid to have any value):
```
[cts.https.html?q=webgpu:api,operation,adapter,requestDevice:features,known:*]
  disabled: reasons for being disabled
```

**Comment by jimblandy** [comment]
@sagudev Just FYI, Erich's on vacation until next Wednesday, so you probably won't get a response here until then.

**Comment by sagudev** [comment]
> @sagudev Just FYI, Erich's on vacation until next Wednesday, so you probably won't get a response here until then.

Thanks for letting me know.

**Comment by ErichDonGubler** [comment]
Thanks for the assist, @jimblandy! 🙂

**Comment by ErichDonGubler** [comment]
@sagudev: RE: adding `FAIL` to the test outcome data model: This is an interesting weirdness in WPT. My understanding is that `expected` outcomes in tests are a strict superset of the ones that can be discovered in subtests (CC @jgraham for clarity). I think it's clear that we need to add it. PRs welcome! I don't think I'm going to be able to prioritize it for a while, but I should have bandwidth for review. The code you linked to (https://github.com/ErichDonGubler/moz-webgpu-cts/commit/e90940f21efb0748346c2e87c9d3954417392711) LGTM, so I bet we can start with that.

**Comment by ErichDonGubler** [comment]
@sagudev: Can you please clarify what you mean by the following?

> so we will probably need to handle such cases as subtest altogether.

**Comment by sagudev** [comment]
Currently no, but I am very pleased with experiments I did with it (it's so much faster than `./mach update-wpt` we have), although I needed wptreports we don't normally do in CI. I am currently investigating some rare CRASHes, before I can return to my PR here.

**Comment by sagudev** [comment]
What I discovered is that all valid values for subtests are also valid for test that have no subtests. You can take a look at PR how I hacked around this.
